# Generated by Django 5.2.10 on 2026-01-07 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='open_id',
        ),
        migrations.AddField(
            model_name='document',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token ZapSign'),
        ),
        migrations.AddField(
            model_name='document',
            name='sign_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link de Assinatura'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.company'),
        ),
        migrations.AlterField(
            model_name='document',
            name='signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.signer'),
        ),
    ]
