# Generated by Django 5.2.10 on 2026-01-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_company_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='ai_missing_topics',
            new_name='missing_topics',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='ai_summary',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='document',
            name='sign_url',
        ),
        migrations.AddField(
            model_name='document',
            name='insights',
            field=models.TextField(blank=True, null=True),
        ),
    ]
