# Generated by Django 5.2.10 on 2026-01-08 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='missing_topics',
        ),
        migrations.AlterField(
            model_name='document',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='document',
            name='open_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='token',
            field=models.CharField(default='temp', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signer',
            name='token',
            field=models.CharField(default='temp', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
